#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
FROM ascent/ascent-base

ENV JAR_FILE "target/${rootArtifactId}.jar"
ADD target/${rootArtifactId}.jar ${symbol_dollar}JAR_FILE

