version: '3.3'
services: 
   ${artifactId}:
    build:
        context: .
    image: ascent/${artifactId}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot

networks: 
 ascentnet: 
    external:
      name: ascentplatformdockerbuild_ascentnet